###

GET http://localhost:3000

###

GET http://localhost:3000/ciclo/listar

###
GET http://localhost:3000/ciclo/listar/1/2/3

###
POST http://localhost:3000/ciclo/cadastar
Content-Type: application/json

{
    "data": "2021/04/12" ,
    "creditos": 
        [
            {
                "nome": "Salário",
                "valor": 5500
            },
            {
                "nome": "Investimento",
                "valor": 50
            }
        ],
        "debitos": 
        [
            {
                "nome": "Luz",
                "valor": 350,
                "status": "PAGO"
            },
            {
                "nome": "Agua",
                "valor": 120,
                "status": "PENDENTE"
            }
        ]            
    
}